version: "3"
services:
  web:
    build: .
    command: bundle exec rackup --host 0.0.0.0 --port 3000
    volumes:
      - .:/app
      - bundle-data:/usr/local/bundle
    working_dir: /app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=pguser
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - SERVICE_ACCOUNT_CREDENTIAL_JSON
      - ADMIN_USERS
      - OREORE_API_KEY
    tty: true
    stdin_open: true
    ports:
      - 3000:3000

volumes:
  bundle-data:
    driver: local
  pg-data:
    driver: local
